name: Docker Build & Push

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      DOCKERFILE_FILEPATH:
        required: true
        type: string
      DOCKER_BUILD_CONTEXT_PATH:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      published_image_path: ${{ steps.push.outputs.published_image_path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/${{ inputs.IMAGE_NAME }}
          VERSION=${GITHUB_RUN_ID}

          echo "Building image: $IMAGE_ID:$VERSION"
          docker build ${{ inputs.DOCKER_BUILD_CONTEXT_PATH }} \
            --file ${{ inputs.DOCKERFILE_FILEPATH }} \
            --tag $IMAGE_ID:$VERSION \
            --tag $IMAGE_ID:latest \
            --label "runnumber=${GITHUB_RUN_ID}"

      - name: Push Docker Image
        id: push
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/${{ inputs.IMAGE_NAME }}
          VERSION=${GITHUB_RUN_ID}

          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest

          # output key must match job outputs (lowercase)
          echo "published_image_path=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT

