name: Docker Build & Push

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      DOCKERFILE_FILEPATH:
        required: true
        type: string
      DOCKER_BUILD_CONTEXT_PATH:
        required: true
        type: string
    secrets:
      GHCR_TOKEN:
        required: true
    outputs:
      published_image_path:                    # ✅ Expose output to caller
        description: "Published Docker image path"
        value: ${{ jobs.build_and_push.outputs.published_image_path }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      published_image_path: ${{ steps.push.outputs.published_image_path }}   # ✅ Job-level output
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/${{ inputs.IMAGE_NAME }}
          VERSION=${GITHUB_RUN_ID}

          echo "Building image: $IMAGE_ID:$VERSION"
          docker build ${{ inputs.DOCKER_BUILD_CONTEXT_PATH }} \
            --file ${{ inputs.DOCKERFILE_FILEPATH }} \
            --tag $IMAGE_ID:$VERSION \
            --tag $IMAGE_ID:latest \
            --label "runnumber=${GITHUB_RUN_ID}"

      - name: Push Docker Image
        id: push
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/${{ inputs.IMAGE_NAME }}
          VERSION=${GITHUB_RUN_ID}

          echo "Pushing image: $IMAGE_ID:$VERSION"
          docker push $IMAGE_ID:$VERSION

          echo "Also pushing image: $IMAGE_ID:latest"
          docker push $IMAGE_ID:latest

          echo "published_image_path=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT  # ✅ Set lowercase output
